from cmath import asin, sinh
# при cmath (комплексные числа) всегда будет выводиться результат
print('Вариант 7')
print('ЗАДАНИЕ. Найдите значения выражений:')
print ('G = 5(27 * a^2 - 51 * a * x + 20 * x^2)/-10 * a^2 + 21 * a * x + 27 * x^2)')
print ('F = sinh(2 * a^2 + 21 * a * x + 10 * x^2)')
print ('Y = -asin(4 * a^2 - 3 * a * x - 7 * x^2)')
print('РЕШЕНИЕ:')
x = float(input('Введите значение x:'))
a = float(input('Введите значение a:'))
G = (5 * (27 * a**2 - 51 * a * x + 20 * x**2))/(-10 * a**2 + 21 * a * x + 27 * x**2)
F = sinh(2 * a**2 + 21 * a * x + 10 * x**2)
Y = -asin(4 * a**2 - 3 * a * x - 7 * x**2)
print('ОТВЕТ:')
print('G = {}, F = {}, Y = {}'.format(G, F, Y))
